[features]
seeds = false
[programs.localnet]
vnft = "AHqPK6YeALn9xFEVqUvN41vsRxrWypWoWHjng1jSgZDj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/v4zha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
